implement multiserver support

diff --git a/installer/bootstrap b/installer/bootstrap
--- a/installer/bootstrap
+++ b/installer/bootstrap
@@ -7,12 +7,14 @@ TTY="/dev/$(ps -p $$ -o tty=)"
 
 INSTALL_DIR='/var/lib/minecraft'
 DEPLOY_DIR='deploy'
+declare -i SERVER_PORT_OFFSET=25500
 
 ################################################################
 # Helper functions
 
 function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
 function status() { echo "${had_status+$'\n'}[1;33m$*[m"; had_status=1; }
+function substatus() { echo "[32m$*[m"; }
 function flush_stdin() { while read -r -t 0.01 empty_stdin < "$TTY"; do true; done; }
 function ask() {
 	local response
@@ -157,61 +159,89 @@ fi
 cd "$DEPLOY_DIR" \
 	|| die "Could not change into deploy directory"
 
-#####################################################
-status "Configuring server"
-#####################################################
 
-install_folder installer/default_config/server "$INSTALL_DIR/$DEPLOY_DIR/server"
+################################################################
+# Setup Velocity Proxy Server
+status "Setting up Velocity proxy server"
 
-install_file <(echo "eula=true") server/eula.txt minecraft: 600
-
+# generate and deploy velocity secret
 VELOCITYSECRET=$(openssl rand -base64 16) \
 	|| die "Could not generate velocity secret"
 install_file <(echo -n "$VELOCITYSECRET") proxy/forwarding.secret minecraft: 600
-sed -i 's|{{VELOCITYSECRET}}|'"$VELOCITYSECRET"'|' server/config/paper-global.yml \
-	|| die "Could not insert velocity secret in paper-global.yml"
 
-echo "Depending on your player base, you might want to allow certain gamplay"
-echo "exploits on your server. These are fixed by default in PaperMC, but would"
-echo "allow your players to build certain vanilla machines (TNT blast chambers,"
-echo "bedrock removal, ...). My personal recommendation is to answer with yes"
-echo "to all of these questions."
-echo
+# deploy default velocity config
+install_folder "installer/default_config/proxy" "proxy"
 
-if ask "Allow headless pistons and bedrock breaking?"; then
-	sed -i 's|allow-headless-pistons: false|allow-headless-pistons: true|' server/config/paper-global.yml \
-		|| die "Could not replace allow-headless-pistons config"
-	sed -i 's|allow-permanent-block-break-exploits: false|allow-permanent-block-break-exploits: true|' server/config/paper-global.yml \
-		|| die "Could not replace allow-permanent-block-break-exploits config"
-fi
+################################################################
+# Setup backend Minecraft Server
 
-if ask "Allow piston TNT duping?"; then
-	sed -i 's|allow-piston-duplication: false|allow-piston-duplication: true|' server/config/paper-global.yml \
-		|| die "Could not replace allow-piston-duplication config"
-fi
+status "Setting up backend minecraft server"
 
-if ask "Enable Anti-XRAY?"; then
-	sed -i 's|false # ANTI_XRAY|true|' server/config/paper-world-defaults.yml \
-		|| die "Could not replace ANTI_XRAY config"
-else
-	sed -i 's|false # ANTI_XRAY|false|' server/config/paper-world-defaults.yml \
-		|| die "Could not replace ANTI_XRAY config"
-fi
+# variable amount of server names
+SERVER_NAMES=(backend)
 
-if ask "Replenish loot in loot chests after 1-2 realtime days?"; then
-	sed -i 's|auto-replenish: false|auto-replenish: true|' server/config/paper-world-defaults.yml \
-		|| die "Could not replace auto-replenish config"
-fi
+# make base server directory
+mkdir servers
+chown minecraft: servers
+chmod 700 servers
 
-if ask "Disable hopper item move event to reduce lag?"; then
-	sed -i 's|disable-move-event: false|disable-move-event: true|' server/config/paper-world-defaults.yml \
-		|| die "Could not replace disable-move-event config"
-fi
+declare -i server_num=1
+for server_name in $SERVER_NAMES; do
+	install_folder installer/default_config/server "servers/$server_name"
 
-if ask "Increase view-distance to 15 chunks?"; then
-	sed -i 's|view-distance=10|view-distance=15|' server/server.properties \
-		|| die "Could not replace view-distance config"
-fi
+	install_file <(echo "eula=true") servers/"$server_name"/eula.txt minecraft: 600
+
+	substatus "Configuring $server_name server"
+
+	sed -i 's|{{SERVER_PORT}}|'"$(($SERVER_PORT_OFFSET+$server_num))"'|' "servers/$server_name"/server.properties \
+		|| die "Could not insert server port into server.properties"
+
+	sed -i 's|{{VELOCITYSECRET}}|'"$VELOCITYSECRET"'|' servers/"$server_name"/config/paper-global.yml \
+		|| die "Could not insert velocity secret in paper-global.yml"
+
+	echo "Depending on your player base, you might want to allow certain gamplay"
+	echo "exploits on your server. These are fixed by default in PaperMC, but would"
+	echo "allow your players to build certain vanilla machines (TNT blast chambers,"
+	echo "bedrock removal, ...). My personal recommendation is to answer with yes"
+	echo "to all of these questions."
+	echo
+
+	if ask "Allow headless pistons and bedrock breaking?"; then
+		sed -i 's|allow-headless-pistons: false|allow-headless-pistons: true|' servers/"$server_name"/config/paper-global.yml \
+			|| die "Could not replace allow-headless-pistons config"
+		sed -i 's|allow-permanent-block-break-exploits: false|allow-permanent-block-break-exploits: true|' servers/"$server_name"/config/paper-global.yml \
+			|| die "Could not replace allow-permanent-block-break-exploits config"
+	fi
+
+	if ask "Allow piston TNT duping?"; then
+		sed -i 's|allow-piston-duplication: false|allow-piston-duplication: true|' servers/"$server_name"/config/paper-global.yml \
+			|| die "Could not replace allow-piston-duplication config"
+	fi
+
+	if ask "Enable Anti-XRAY?"; then
+		sed -i 's|false # ANTI_XRAY|true|' servers/"$server_name"/config/paper-world-defaults.yml \
+			|| die "Could not replace ANTI_XRAY config"
+	else
+		sed -i 's|false # ANTI_XRAY|false|' servers/"$server_name"/config/paper-world-defaults.yml \
+			|| die "Could not replace ANTI_XRAY config"
+	fi
+
+	if ask "Replenish loot in loot chests after 1-2 realtime days?"; then
+		sed -i 's|auto-replenish: false|auto-replenish: true|' servers/"$server_name"/config/paper-world-defaults.yml \
+			|| die "Could not replace auto-replenish config"
+	fi
+
+	if ask "Disable hopper item move event to reduce lag?"; then
+		sed -i 's|disable-move-event: false|disable-move-event: true|' servers/"$server_name"/config/paper-world-defaults.yml \
+			|| die "Could not replace disable-move-event config"
+	fi
+
+	if ask "Increase view-distance to 15 chunks?"; then
+		sed -i 's|view-distance=10|view-distance=15|' servers/"$server_name"/server.properties \
+			|| die "Could not replace view-distance config"
+	fi
+	server_num+=1
+done
 
 echo
 
@@ -240,8 +270,12 @@ echo
 
 postponed_service_message=""
 if ask "Enable and start system services now?"; then
-	systemctl enable --now minecraft-server minecraft-proxy < "$TTY" \
+	systemctl enable --now minecraft-proxy < "$TTY" \
 		|| die "Error while enabling services"
+	for server_name in $SERVER_NAMES; do
+		systemctl enable --now minecraft-server@"$server_name" < "$TTY" \
+			|| die "Error while enabling server named $server_name"
+	done
 else
 	postponed_service_message="
 You have postponed enabling the system services. Make sure to execute the
